<h1 class="display-4">Contato</h1>
<p class="lead mb-4">Você pode entrar em contato pelo formulário abaixo:</p>

<div class="row">
	
	<div class="col-sm-6">		
		<form action="/contato/" method="POST" class="">
			<div class="form-group">				
				<input type="text" class="form-control" placeholder="Nome">
			</div>	
			<div class="form-group">				
				<input type="text" class="form-control" placeholder="E-mail">
			</div>
			<div class="form-group">				
				<textarea name="" class="form-control" cols="30" rows="4" placeholder="Mensagem"></textarea>
			</div>
			<button type="submit" class="btn btn-primary">Enviar Contato <i class="fa fa-paper-plane fa-fw"></i></button>
		</form>			
	</div>

</div>

