	
<div class="row mt-5">
	<div class="col-sm"></div>
	<div class="col-sm-8 text-center">
		<img src="/images/fernandovaller.jpg" class="rounded-circle" alt="Fernando Valler">
		<h1>Fernando Valler</h1>
		<h4>Programador Web</h4>
		<p class="lead">Sou programador web, motivado por desafios e sempre buscando aprender algo novo. Aqui você pode encontrar alguns projetos.</p>
	</div>
	<div class="col-sm"></div>
</div>
		
