<h1 class="display-4">Projetos</h1>
<p class="lead mb-5">Conheça alguns dos meus projetos.</p>

<div class="row my-4">
	
	<?php for ($i = 0; $i < 5; $i++) { ?>
	<div class="col-sm-4 mb-4">
		<div class="card">
			<img src="/uploads/p-1.png" class="card-img-top">
			<div class="card-body">
				<h4 class="card-title text-info">Digital Ocean</h4>
				<p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia, distinctio. Magnam aperiam vel impedit dolores atque nisi officia deserunt iste numquam quis.</p>
			</div>	
			<div class="card-footer">
				<a href="/projetos/<?=$i?>" class="btn btn-info btn-block">Saiba mais</a>
			</div>
		</div>		
	</div>	
	<?php } ?>


</div>