
<blockquote>
	<h1 class="display-4">Serviços</h1>
	<p class="lead">Listo abaixo alguns dos principais serviços</p>	
</blockquote>


<div class="row my-5">

	<div class="col-sm-4 mb-3">
		<div class="card card-servicos">
			<div class="card-body">
				<h4 class="card-title mb-4 text-info">Servidor Cloud</h4>
				<p class="card-subtitle">Migre a infraestrutura do seu site para servidoeres proprio na nuvem como <a href="https://aws.amazon.com/pt/" target="_blank">Amazon</a> e <a href="https://www.digitalocean.com/" target="_blank">Digital Ocean</a>.</p>
			</div>
		</div>
	</div>	

	<div class="col-sm-4 mb-3">
		<div class="card card-servicos">
			<div class="card-body">
				<h4 class="card-title mb-4 text-info">Sistemas Web</h4>
				<p class="card-subtitle">Trabalho com o desenvolvimento de sites e sistemas para Web, Sistema comerciais como Controle de Estoque, Controle Financeiro e Controle Imobiliário.</p>
			</div>
		</div>
	</div>	

	<div class="col-sm-4 mb-3">
		<div class="card card-servicos">
			<div class="card-body">
				<h4 class="card-title mb-4 text-info">Projetos Personalizados</h4>
				<p class="card-subtitle">Você tem uma ideia ou projeto que gostaria de transformar em sistema, acredito que posso lhe ajudar no desenvolvimento de uma solução para sua empresa.</p>
			</div>
		</div>
	</div>

</div>

