<!DOCTYPE html>
<html lang="pt-br">
	<head>		
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Fernando Valler - Programador Web</title>	
		<link rel="stylesheet" href="/node_modules/font-awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.min.css">
		<link rel="stylesheet" href="/css/style.css?v=<?=filemtime('css/style.css')?>">
	</head>
	<body>
		
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
			<div class="container">
				<a class="navbar-brand" href="/">Fernando Valler</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSite">					
					<ul class="navbar-nav ml-auto">						
						<li class="nav-item active"><a href="/home" class="nav-link"><i class="fa fa-home fa-fw"></i> Home</a></li>
						<li class="nav-item ml-1"><a href="/projetos" class="nav-link"><i class="fa fa-database fa-fw"></i> Projetos</a></li>
						<li class="nav-item ml-1"><a href="/servicos" class="nav-link"><i class="fa fa-rocket fa-fw"></i> Serviços</a></li>						
						<li class="nav-item ml-1"><a href="/contato" class="nav-link"><i class="fa fa-envelope-o fa-fw"></i> Contato</a></li>
					</ul>
				</div>				
			</div> <!-- container -->
		</nav>

		<div class="apresentacao">
			<div class="container p-3" id="paginas">		