
<div class="row my-4">

	<div class="col-sm-8">		
			
		<h1 class="display-4">Controle de Estoque</h1>
		<p class="lead mb-3">Sistema desenvolvido em PHP e MySQL</p>

		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, aut! Sequi, harum, placeat. Libero consectetur optio ut explicabo incidunt blanditiis excepturi ex illo, aperiam, reiciendis consequuntur asperiores deleniti molestiae aspernatur.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, aut! Sequi, harum, placeat. Libero consectetur optio ut explicabo incidunt blanditiis excepturi ex illo, aperiam, reiciendis consequuntur asperiores deleniti molestiae aspernatur.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, aut! Sequi, harum, placeat. Libero consectetur optio ut explicabo incidunt blanditiis excepturi ex illo, aperiam, reiciendis consequuntur asperiores deleniti molestiae aspernatur.</p>
	</div>	

	<div class="col-sm-4 bg-silver p-3 border">
		<div class="mb-3"><img src="/uploads/p-1.png" class="img-fluid"></div>
		<a href="#" class="btn btn-primary btn-block">Demostração Online</a>
	</div>

</div>